gcpug/handy-spanner

fake/example_test.go, server/database.go, server/query.go
=> fix lint errors

fake/server.go, server/database.go, server/database_test.go, server/query.go, server/query_test.go, server/server.go, server/value.go
Introduce Value struct for raw data with ValueType in order to do type inference for params correctly.
=> Value with type

server/database.go
When validateFn returns error, write method does not return as error. The current validate function is broken in the first place, so remove them and handle the special case in buildQuery instead.
=> remove validateFn in write to fix wrong error handling

README.md, server/database_test.go, server/query.go
Implement Scalar Subquery, Exists, Subquery in IN condition.
Now probably all subquery patterns are supported.
=> implement remaining subquery patterns

README.md, server/database_test.go, server/query.go
Implement join with USING and join with paren (I'm not about paren pattern...).
=> implement remaining join patterns

server/database_function.go, server/database_test.go, server/query.go, server/value.go
Add MIN, MAX, AVG, SUM, ENDS_WITH, CONCAT
=> add more functions

server/database.go, server/database_test.go, server/query.go
Implement UNION partially. INTERSECT and EXCEPT are not supported.
=> rough implementation of union

README.md, server/database_test.go, server/query.go, server/value.go
Support INTERSECT and EXCEPT and check type compatibility for columns.
=> implement set operations

server/server.go, server/server_test.go
Implement session APIs
* BatchCreateSessions
* GetSession
* ListSessions
=> implement sessions APIs

server/database_test.go, server/query.go, server/table.go
`UNNEST() AS name` is handled as alias of table name with unnamed column so far, but it should be alias of column name in unnamed table.
Now `SELECT x FROM UNNEST() AS x` can access unnested values.
=> refactor table view and fix unnest behavior

fake/integration_test.go, server/query.go
add "DISTINCT" keyword to execute query when it is used in input query
=> Enable DISTINCT

server/database_function.go, server/database_test.go, server/query.go, server/value.go
Support CAST for almost all types based on the doc https://cloud.google.com/spanner/docs/functions-and-operators#conversion-rules
=> Support CAST

server/database.go, server/database_query_test.go, server/database_test.go, server/query.go, server/server.go, server/server_test.go, server/table.go, server/value.go
support both struct literal and select as struct
=> Support struct in query

fake/integration_test.go, server/server.go, server/server_test.go
=> Support CreateDatabase operation

README.md, cmd/handy-spanner/main.go, server/database_query_test.go, server/query.go, server/value.go
* Fix FROM UNNEST behavior
* Update README to describe about feature requests and usages
=> Improve struct compatiblity

go.mod, go.sum, server/server.go
backup APIs are added yesterday.
https://github.com/googleapis/googleapis/commit/309b899ca18a4c604bce63882a161d44854da549
https://code-review.googlesource.com/c/gocloud/+/53110/3/spanner/admin/database/apiv1/database_admin_client.go
=> Update genproto with umimplemented backup funcs

server/database.go, server/database_test.go
Add constraint for sized string such as `Value STRING(16)`.
=> add size constraint

server/database_function.go
**WHAT**
Add support for CURRENT_TIMESTAMP function.
=> Add CURRENT_TIMESTAMP function

server/database.go, server/database_test.go
fixes https://github.com/gcpug/handy-spanner/issues/85
=> support default expression

server/database_function.go, server/database_query_test.go, server/value.go
This PR adds support for GENERATE_ARRAY
=> Support GENERATE_ARRAY
